### ISSUE TITLE
Data folder permissions issues

### ISSUE THREAD

**Issue by lladdy** [aiarena/aiarena-docker-base#8]
It appears data permissions might not be set correctly if the bot doesn't have a data file to download or something.

From Infy:

> I think there is something wrong with the permissions to the data folder
> it seems to me like I have to upload empty data folder before the permissions start working
```
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    main()
  File "run.py", line 15, in main
    result, opponentid = run_ladder_game(zerg_bot)
  File "/home/bot_player1/ladder.py", line 64, in run_ladder_game
    ensure_directories()
  File "/home/bot_player1/ladder.py", line 110, in ensure_directories
    os.mkdir(folder)
PermissionError: [Errno 13] Permission denied: 'data/games'```

**Comment by lladdy** [comment]
Presumed resolved.
